version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: alx_postgres
    restart: always
    environment:
      POSTGRES_DB: alx_crm_db
      POSTGRES_USER: alx_user
      POSTGRES_PASSWORD: alx_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: alx_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
